### ISSUE TITLE
outline 1.5.0 disconnect immediately on windows 10

### ISSUE THREAD

**Issue by koohsaran** [Jigsaw-Code/outline-client#1002]
HI
I have some outline servers on my android outline and same on my pc 
servers connect and work perfect on android device but on my pc with win 10, all servers disconnect immediately 
so the problem is not from servers, its from my windows 10
I found this error in windows event viewer :
Failed to handle connection: System.IO.IOException: Pipe is broken.
   at System.IO.Pipes.PipeStream.WinIOError(Int32 errorCode)
   at System.IO.Pipes.PipeStream.BeginWriteCore(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state)
   at System.IO.Pipes.PipeStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Pipes.PipeStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at OutlineService.OutlineService.WriteResponse(ServiceResponse response)
   at OutlineService.OutlineService.HandleConnection(IAsyncResult result)

please help me

**Comment by belyaevsa** [comment]
Please, run as Administrator application. It has helped me
