### ISSUE TITLE
Unexpected error: smartdnsblock failed

### ISSUE THREAD

**Issue by seakfind** [Jigsaw-Code/outline-client#1078]
**Test procedure**

1. Install Windows 11 in a virtual machine
2. Install vc_redist.x64.exe
3. Install Outline Manager
4. Configure Ubuntu 20.04 server with Docker preinstalled
5. Paste API URL into Outline Manager
6. Install Outline Client
7. Add server access key to client
8. Attempt to connect from client to server

**Expected result**

Client connects to server

**Actual result**

Unexpected error. 

Sorry, an unexpected error occurred.

Wireshark shows TCP exchange with server, followed by 1 UDP packet from client to server, followed by 1 UDP packet back from server to client.

Windows Event Viewer, Windows Logs > Application, shows:

Failed to handle connection: System.IO.IOException: Pipe is broken.
   at System.IO.Pipes.PipeStream.WinIOError(Int32 errorCode)
   at System.IO.Pipes.PipeStream.BeginWriteCore(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state)
   at System.IO.Pipes.PipeStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Pipes.PipeStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at OutlineService.OutlineService.WriteResponse(ServiceResponse response)
   at OutlineService.OutlineService.HandleConnection(IAsyncResult result)
   
preceded by:

request failed: could not start smartdnsblock: smartdnsblock failed (stdout: , (stderr: )

**Workaround**

Install Shadowsocks on server:

wget https://raw.githubusercontent.com/teddysun/shadowsocks_install/master/shadowsocks-libev-debian.sh

chmod +x shadowsocks-libev-debian.sh

./shadowsocks-libev-debian.sh

Install Shadowsocks on client from https://github.com/shadowsocks/shadowsocks-windows/releases

**Result of Workaround**

Shadowsocks works fine.

**Comment by seakfind** [comment]
As per https://github.com/Jigsaw-Code/outline-client/issues/782 it is `vc_redist.x86.exe` that must be installed to fix the problem, even on a 64-bit machine.
