### ISSUE TITLE
Storybook Build issues with Cygwin in Windows10

### ISSUE THREAD

**Issue by hugetiny** [Jigsaw-Code/outline-client#1346]
**Describe the issue**
```
$ npm install
```
```
$ npm run action src/www/storybook
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> action
> node ./src/build/run_action.mjs "src/www/storybook"


       / __ \| |  | |__   __| |    |_   _| \ | |  ____|
      | |  | | |  | |  | |  | |      | | |  \| | |__
      | |  | | |  | |  | |  | |      | | | . ` |  __|
      | |__| | |__| |  | |  | |____ _| |_| |\  | |____
       \____/ \____/   |_|  |______|_____|_| \_|______|

  =========================================================
               © The Outline Authors, 2022
  =========================================================

▶ action(src/www/storybook):
  Web Dev Server started...
    Root dir: C:\Users\hugetiny\WebstormProjects\outline-client\src\www
    Local:    http://localhost:8002/
    Network:  http://192.168.0.101:8002/
  Error: spawn C:\Users\hugetiny\WebstormProjects\outline-client\node_modules\esbuild\esbuild.exe ENOENT
      at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
      at onErrorNT (node:internal/child_process:478:16)
      at processTicksAndRejections (node:internal/process/task_queues:83:21) {
    errno: -4058,
    code: 'ENOENT',
    syscall: 'spawn C:\\Users\\hugetiny\\WebstormProjects\\outline-client\\node_modules\\esbuild\\esbuild.exe',
    path: 'C:\\Users\\hugetiny\\WebstormProjects\\outline-client\\node_modules\\esbuild\\esbuild.exe',
    spawnargs: [ '--service=0.12.29', '--ping' ]
  }
  Error while handling server request.
  Error: The service was stopped
      at C:\Users\hugetiny\WebstormProjects\outline-client\node_modules\esbuild\lib\main.js:1258:29
      at C:\Users\hugetiny\WebstormProjects\outline-client\node_modules\esbuild\lib\main.js:611:9
      at Socket.afterClose (C:\Users\hugetiny\WebstormProjects\outline-client\node_modules\esbuild\lib\main.js:589:7)
      at Socket.emit (node:events:539:35)
      at endReadableNT (node:internal/streams/readable:1345:12)
      at processTicksAndRejections (node:internal/process/task_queues:83:21)
  Error while handling server request.
  Error: The service was stopped
      at C:\Users\hugetiny\WebstormProjects\outline-client\node_modules\esbuild\lib\main.js:1258:29
      at C:\Users\hugetiny\WebstormProjects\outline-client\node_modules\esbuild\lib\main.js:611:9
      at Socket.afterClose (C:\Users\hugetiny\WebstormProjects\outline-client\node_modules\esbuild\lib\main.js:589:7)
      at Socket.emit (node:events:539:35)
      at endReadableNT (node:internal/streams/readable:1345:12)
      at processTicksAndRejections (node:internal/process/task_queues:83:21)
  Error while handling server request.
  Error: The service was stopped
      at C:\Users\hugetiny\WebstormProjects\outline-client\node_modules\esbuild\lib\main.js:1258:29
      at C:\Users\hugetiny\WebstormProjects\outline-client\node_modules\esbuild\lib\main.js:611:9
      at Socket.afterClose (C:\Users\hugetiny\WebstormProjects\outline-client\node_modules\esbuild\lib\main.js:589:7)
      at Socket.emit (node:events:539:35)
      at endReadableNT (node:internal/streams/readable:1345:12)
      at processTicksAndRejections (node:internal/process/task_queues:83:21)

```

**Environment**
 - OS: Windows10
 - NPM version 8.11.0
 - Node.js version 16.15.1

**Comment by hugetiny** [comment]
still failed after```npm run reset```
