### ISSUE TITLE
Running Outline Client stopped on my Debian x64.

### ISSUE THREAD

**Issue by CourteousSleet** [Jigsaw-Code/outline-client#1560]
**Describe the bug**
When you normally click connect, an error began to appear asking you to exit the application and start it again. However, the problem does not disappear.

**To Reproduce**
I run it my Debian KDE x64 laptop. And it worked until today.

**Expected behavior**
I expected usual connection to my VPN

**Screenshots**
````
Outline is starting
loading web app from file:///tmp/.mount_OutliniebiJq/resources/app.asar/www/index_electron.html?appName=Outline
Could not load active tunnel:  [Error: ENOENT: no such file or directory, open '/home/ian/.config/Outline/connection_store'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/ian/.config/Outline/connection_store'
}
Checking for update
Update for version 1.9.0 is not available (latest version: 1.9.0, downgrade is disallowed).
connecting to 59f86756-132a-4971-a095-4b74371337e8...
using tun2socks to check connectivity
[EXIT - tun2socks]: Exited with code 4
connectivity check error: Error: Process terminated by non-zero exit code: 4
UDP support: false
starting routing daemon
tun2socks started
could not connect: Error (configure system proxy failure)
Error occurred in handler for 'outline-ipc-start-proxying': Error: unknown NativeError Error
    at t.toErrorCode (/tmp/.mount_OutliniebiJq/resources/app.asar/build/electron/electron/index.js:2:451500)
    at /tmp/.mount_OutliniebiJq/resources/app.asar/build/electron/electron/index.js:2:438137
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async node:electron/js2c/browser_init:189:563
[EXIT - tun2socks]: Exited with code 0
tun2socks exited with no errors
could not stop routing: Write failed
disconnected from 59f86756-132a-4971-a095-4b74371337e8
````

**Client System (please complete the following information):**
 - Outline Client Version [Linux 1.9.0]
 - Your Operating System: [Debian KDE 5.10.0-20-amd64]

**Submit Feedback**
Please submit feedback through the app and label it with this issue number.

**Additional context**

**Comment by CourteousSleet** [comment]
So, after several reboots problem is gone.

**Comment by sandofvega** [comment]
Rebooting is not the solution.

**Comment by coalest** [comment]
I also have this same problem. Have to restart my computer quite often because of it :cry: 

Outline Client: Version 1.13.1 (476278)
Operating system: Debian GNU/Linux 12 (bookworm) 6.1.0-20-amd64

**Comment by q4a** [comment]
Sometimes I have same problem. I'll write the reasons why I have such a problem, the solution and a wish to the developers.

 I'm using Ubuntu 24.10 and Outline Client: Version 1.14.0  (480310), but Debian should have same behavior.
In normal way if you already used Outline it will create connection `outline-tun0` that will be enabled after boot. 
```
$ nmcli con
NAME                UUID                                  TYPE      DEVICE       
Wired connection 1  779af331-b706-3d2f-b510-aed2be49a6a5  ethernet  enp2s0       
lo                  d7ec8725-7d8f-42c4-8569-42508855b7b5  loopback  lo           
outline-tun0        9940e3af-4432-4168-975e-74a6fd3b1337  tun       outline-tun0
```
Also there is few outline services:
```
$ systemctl list-units | grep outline
  sys-devices-virtual-net-outline\x2dtun0.device                                           loaded active plugged   /sys/devices/virtual/net/outline-tun0
  sys-subsystem-net-devices-outline\x2dtun0.device                                         loaded active plugged   /sys/subsystem/net/devices/outline-tun0
  outline_proxy_controller.service                                                         loaded active running   Outline Proxy Routing Controller
```
When I need to connect other VPN (for work) sometimes I have to disconnect outline-tun0:
```
$ nmcli con
NAME                UUID                                  TYPE      DEVICE       
Wired connection 1  779af331-b706-3d2f-b510-aed2be49a6a5  ethernet  enp2s0       
lo                  d7ec8725-7d8f-42c4-8569-42508855b7b5  loopback  lo           
```
But when I starting Outline VPN again it does not check, if I have outline-tun0 connection and I'm getting error.
```
[tun2socks] - checking connectivity ...
[tun2socks - EXIT]: Exited with code 0
UDP support: true
starting routing daemon
[tun2socks] - starting to route network traffic ...
[tun2socks] - started
could not connect: Error: configure system proxy failure
    at Socket.<anonymous> (/tmp/.mount_OutlinJYXcqa/resources/app.asar/output/client/electron/index.js:2:678072)
    at Object.onceWrapper (node:events:646:26)
    at Socket.emit (node:events:526:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
Error occurred in handler for 'outline-ipc-start-proxying': Error: configure system proxy failure
    at Socket.<anonymous> (/tmp/.mount_OutlinJYXcqa/resources/app.asar/output/client/electron/index.js:2:678072)
    at Object.onceWrapper (node:events:646:26)
    at Socket.emit (node:events:526:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
[tun2socks - EXIT]: Exited with code 0
[tun2socks] - exited with no errors
could not stop routing: Write failed
disconnected from 2d4c40cf-18e8-4b47-accf-bf911fe659d5
```
So I need to restart outline_proxy_controller (it is running, but still).
```
$ sudo systemctl restart outline_proxy_controller.service
```
Then outline-tun0 connection is back and I can connect to Outline VPN.
More useful info written in Readme:
https://github.com/Jigsaw-Code/outline-apps/blob/master/client/electron/linux_proxy_controller/README.md

To developers: please, add check if outline-tun0 connection exist and connected when users start Outline VPN client. Then people can just restart client if something went wrong.
