### ISSUE TITLE
Linux client can't connect

### ISSUE THREAD

**Issue by Psijic** [Jigsaw-Code/outline-client#1776]
Few months ago I used Outline client without major issues, then disconnections happened more often. Currently Linux client can't connect at all while it's fine with Android client and the same key.

```
connecting to c1876827-21cd-4bd4-a6ba-1de1146aede7...
using tun2socks to check connectivity
[EXIT - tun2socks]: Exited with code 0
UDP support: true
starting routing daemon
could not connect: Error (configure system proxy failure)
Error occurred in handler for 'outline-ipc-start-proxying': Error: unknown NativeError Error
    at t.toErrorCode (/tmp/.mount_Outlinr4AX2Y/resources/app.asar/build/electron/electron/index.js:2:451561)
    at /tmp/.mount_Outlinr4AX2Y/resources/app.asar/build/electron/electron/index.js:2:438444
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async node:electron/js2c/browser_init:189:563
[EXIT - tun2socks]: Killed by signal SIGTERM
tun2socks terminated due to Error: Process terminated by signal: SIGTERM
could not stop routing: Write failed
disconnected from c1876827-21cd-4bd4-a6ba-1de1146aede7
```
OpenSuse TW, latest client.

Same time I found I can use Outline client on my PC via Android Emulator without any Linux proxy configurations as well.

**Comment by maddyhof** [comment]
Thanks for reaching out! We just released Client v1.12.1 which should fix this problem. Please give that a try and reopen this issue if it's still not working.
