### ISSUE TITLE
ReferenceError: internalBinding is not defined

### ISSUE THREAD

**Issue by hwnahm** [Jigsaw-Code/outline-client#377]
# yarn gulp build --platform=osx
yarn run v1.12.3
$ /Users/peter/devel/outline-client/node_modules/.bin/gulp build --platform=osx
fs.js:25
'use strict';
^

ReferenceError: internalBinding is not defined
    at fs.js:25:1
    at req_ (/Users/peter/devel/outline-client/node_modules/vinyl-fs/node_modules/natives/index.js:137:5)
    at Object.req [as require] (/Users/peter/devel/outline-client/node_modules/vinyl-fs/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/Users/peter/devel/outline-client/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:99)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by xiaooutv** [comment]
也遇到了这个问题，找了下资料，是因为natives这个库版本太低的原因。

解决办法，
编辑文件：package.json
修改第 65 行代码：
`"natives": "1.1.3"`

把1.1.3改为1.1.6后保存，
重新编译。

**Comment by trevj** [comment]
@hwnahm @xiaooutv I'm afraid I don't see this on my system. Which version of Xcode are you using? I'm on 9.4.

**Comment by trevj** [comment]
Closing due to inactivity. @hwnahm Please re-open if you'd like to discuss more.

**Comment by trevj** [comment]
@hwnahm @xiaooutv Apologies, just ran into this myself.

Looks like this is an issue in Node.js 10.14.2 which just hit NVM, and therefore our CB and my development environment:
https://travis-ci.org/Jigsaw-Code/outline-client/jobs/466707582

**Comment by trevj** [comment]
@xiaooutv Many thanks for the pointer, it helped me produce a quick fix.
