### ISSUE TITLE
"The Connection was reset" on windows 10

### ISSUE THREAD

**Issue by vahid-sohrabloo** [Jigsaw-Code/outline-client#399]
On the windows after a few minutes after connection to the server  when leaving the pc for some time, Outline is still connected but there is no internet connection and will see the 
```
The Connection was reset
```
 on the browser and there is no internet, you need to disconnect  the outline and reconnect it again

I found this log on Event Viewer 
```
Failed to handle connection: System.IO.IOException: Pipe is broken.
   at System.IO.Pipes.PipeStream.WinIOError(Int32 errorCode)
   at System.IO.Pipes.PipeStream.BeginWriteCore(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state)
   at System.IO.Pipes.PipeStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Pipes.PipeStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at OutlineService.OutlineService.WriteResponse(ServiceResponse response)
   at OutlineService.OutlineService.HandleConnection(IAsyncResult result)

failed to remove 2000::/4: command exited with 1 (stdout: Element not found., stderr: )

Failed to remove reserved subnets bypass: command exited with 1 (stdout: Element not found., stderr: )

failed to remove 128.0.0.0/1: command exited with 1 (stdout: Element not found., stderr: )

failed to remove 0.0.0.0/1: command exited with 1 (stdout: Element not found., stderr: )
```

**Comment by sailosha** [comment]
double check your windows 10 powersetting.
I always use Ultimate Performance to be default.

**Comment by trevj** [comment]
@vahid-sohrabloo Thanks for the report - and apologies for the slow reply. 

Did @sailosha's suggestion work for you?

Also, earlier this week we released a new version of the client which makes significant changes to how the client communicates with the background service which may help with this:
https://github.com/Jigsaw-Code/outline-client/releases/tag/windows-v1.2.21

**Comment by trevj** [comment]
@vahid-sohrabloo Closing this due to inactivity but please do re-open if you'd like to discuss more.
