### ISSUE TITLE
libss-local.so: No such file or directory

### ISSUE THREAD

**Issue by joeytwiddle** [Jigsaw-Code/outline-client#427]
If I install Outline from the Google Play Store, it works fine.

But when I try to build my own version for Android, I get this message:

> Sorry, an unexpected error occurred. Quitting and restarting may help...

From the Android log, we can see the core error is:

> 12-06 11:25:44.087 27480 28547 E Shadowsocks: Failed to start ss-local
> 12-06 11:25:44.087 27480 28547 E Shadowsocks: java.io.IOException: Cannot run program "/data/app/org.outline.android.client-SCkHIku1UTp3EakjnKZ3zQ==/lib/arm64/libss-local.so": error=2, No such file or directory

Here is more of the log, with context:
<details>
```
$ adb -d logcat | grep -C20 ' I chromium: '
12-06 11:25:44.070 27480 27480 I chromium: [INFO:CONSOLE(1278)] "connecting to server 7851e462-c5bd-4e13-97b7-ae2c170da1ca", source: file:///android_asset/www/cordova_main.js (1278)
12-06 11:25:44.073 27480 27587 D OutlinePlugin: action: start, connection ID: 7851e462-c5bd-4e13-97b7-ae2c170da1ca
12-06 11:25:44.074 27480 28536 D OutlinePlugin: Preparing VPN.
12-06 11:25:44.077   579  1246 D asd_primary_in: L[156]-46.446507db, R[156]-46.446507db
12-06 11:25:44.078 27480 28536 I OutlinePlugin: Starting VPN connection
12-06 11:25:44.079 27480 28536 I VpnTunnelService: Starting connection 7851e462-c5bd-4e13-97b7-ae2c170da1ca.
12-06 11:25:44.082 27480 28547 I Shadowsocks: starting ss-local
12-06 11:25:44.087 27480 28547 E Shadowsocks: Failed to start ss-local
12-06 11:25:44.087 27480 28547 E Shadowsocks: java.io.IOException: Cannot run program "/data/app/org.outline.android.client-SCkHIku1UTp3EakjnKZ3zQ==/lib/arm64/libss-local.so": error=2, No such file or directory
12-06 11:25:44.087 27480 28547 E Shadowsocks: 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
12-06 11:25:44.087 27480 28547 E Shadowsocks: 	at org.outline.shadowsocks.Shadowsocks.start(Shadowsocks.java:57)
12-06 11:25:44.087 27480 28547 E Shadowsocks: 	at org.outline.vpn.VpnTunnelService$1.call(VpnTunnelService.java:266)
12-06 11:25:44.087 27480 28547 E Shadowsocks: 	at org.outline.vpn.VpnTunnelService$1.call(VpnTunnelService.java:262)
12-06 11:25:44.087 27480 28547 E Shadowsocks: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
...
12-06 11:25:44.087 27480 28547 E Shadowsocks: Caused by: java.io.IOException: error=2, No such file or directory
12-06 11:25:44.087 27480 28547 E Shadowsocks: 	at java.lang.UNIXProcess.forkAndExec(Native Method)
12-06 11:25:44.087 27480 28547 E Shadowsocks: 	at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
12-06 11:25:44.087 27480 28547 E Shadowsocks: 	at java.lang.ProcessImpl.start(ProcessImpl.java:128)
12-06 11:25:44.087 27480 28547 E Shadowsocks: 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
12-06 11:25:44.087 27480 28547 E Shadowsocks: 	... 7 more
12-06 11:25:44.088 27480 28547 E VpnTunnelService: Failed to start Shadowsocks.
12-06 11:25:44.090 27480 28536 I VpnTunnel: Disconnecting the tunnel.
12-06 11:25:44.090 27480 27480 D OutlinePlugin: Service broadcast: start, 7851e462-c5bd-4e13-97b7-ae2c170da1ca, 8
12-06 11:25:44.091 27480 28536 I VpnTunnel: Tearing down the VPN.
12-06 11:25:44.096 27480 27480 I HwSecImmHelper: mSecurityInputMethodService is null
12-06 11:25:44.100 27480 27480 D SystemWebChromeClient: file:///android_asset/www/cordova_main.js: Line 1278 : could not connect to server 7851e462-c5bd-4e13-97b7-ae2c170da1ca: ShadowsocksStartFailure
12-06 11:25:44.100 27480 27480 I chromium: [INFO:CONSOLE(1278)] "could not connect to server 7851e462-c5bd-4e13-97b7-ae2c170da1ca: ShadowsocksStartFailure", source: file:///android_asset/www/cordova_main.js (1278)
12-06 11:25:44.101 27480 27587 D OutlinePlugin: action: reportEvents, connection ID: null
```
</details>

----

That was with branch `origin/alalama-android-v1.2.4` but I have the same problem with the latest master fc21a04.

These are the commands I am using to build and install:
```
yarn gulp build --platform=android
adb -d install -r -d platforms/android/app/build/outputs/apk/x86_64/debug/app-x86_64-debug.apk
```

**Comment by joeytwiddle** [comment]
This is easy to resolve. The phone has an ARM cpu, which is why it was trying to run `/lib/arm64/libss-local.so`

My mistake was that I had installed the x86_64 apk, which does not bundle the ARM library.

Although the UI works just fine, the problem appears when trying to open the connection.

**The solution:** adjust my `adb install` to install the ARM apk!

**Comment by trevj** [comment]
@joeytwiddle Glad to hear you figured it out!
