### ISSUE TITLE
[Solved] Building windows client

### ISSUE THREAD

**Issue by hwnahm** [Jigsaw-Code/outline-client#445]
ALL DONE
+ echo '[Done src/electron/build]'
[Done src/electron/build]
  • electron-builder version=20.13.3
  • description is missed in the package.json appPackageFile=/Users/peter/devel/outline/outline-client/build/windows/package.json
  • author is missed in the package.json appPackageFile=/Users/peter/devel/outline/outline-client/build/windows/package.json
  • writing effective config file=build/windows/dist/electron-builder-effective-config.yaml
  • installing production dependencies platform=win32 arch=ia32 appDir=/Users/peter/devel/outline/outline-client/build/windows
  • packaging       platform=win32 arch=ia32 electron=1.8.6 appOutDir=build/windows/dist/win-ia32-unpacked
Error: Exit code: ENOENT. spawn prlctl ENOENT
    at /Users/peter/devel/outline/outline-client/node_modules/builder-util/src/util.ts:124:16
    at exithandler (child_process.js:301:5)
    at ChildProcess.errorhandler (child_process.js:313:5)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:252:12)
    at onErrorNT (internal/child_process.js:421:16)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
From previous event:
    at parseVmList (/Users/peter/devel/outline/outline-client/node_modules/electron-builder-lib/out/vm/ParallelsVm.js:83:17)
    at /Users/peter/devel/outline/outline-client/node_modules/electron-builder-lib/src/vm/vm.ts:25:25
    at Generator.next (<anonymous>)
From previous event:
    at getWindowsVm (/Users/peter/devel/outline/outline-client/node_modules/electron-builder-lib/out/vm/vm.js:76:17)
    at Lazy.WinPackager.vm (/Users/peter/devel/outline/outline-client/node_modules/electron-builder-lib/src/winPackager.ts:60:12)
    at Lazy.get value [as value] (/Users/peter/devel/outline/outline-client/node_modules/lazy-val/src/main.ts:18:23)
    at Lazy.WinPackager.cscInfo (/Users/peter/devel/outline/outline-client/node_modules/electron-builder-lib/src/winPackager.ts:30:11)
    at Lazy.get value [as value] (/Users/peter/devel/outline/outline-client/node_modules/lazy-val/src/main.ts:18:23)
    at Lazy.<anonymous> (/Users/peter/devel/outline/outline-client/node_modules/electron-builder-lib/src/winPackager.ts:94:14)
    at Generator.next (<anonymous>)
From previous event:
    at Lazy.get value [as value] (/Users/peter/devel/outline/outline-client/node_modules/lazy-val/src/main.ts:18:23)
    at /Users/peter/devel/outline/outline-client/node_modules/electron-builder-lib/src/publish/PublishManager.ts:206:25
    at Generator.next (<anonymous>)
From previous event:
    at getAppUpdatePublishConfiguration (/Users/peter/devel/outline/outline-client/node_modules/electron-builder-lib/src/publish/PublishManager.ts:215:2)
    at /Users/peter/devel/outline/outline-client/node_modules/electron-builder-lib/src/publish/PublishManager.ts:84:9
    at Generator.next (<anonymous>)
From previous event:
    at PublishManager.packager.addAfterPackHandler (/Users/peter/devel/outline/outline-client/node_modules/electron-builder-lib/src/publish/PublishManager.ts:91:6)
    at _bluebirdLst.default.each.it (/Users/peter/devel/outline/outline-client/node_modules/electron-builder-lib/src/packager.ts:467:49)
From previous event:
    at Packager.afterPack (/Users/peter/devel/outline/outline-client/node_modules/electron-builder-lib/src/packager.ts:467:28)
    at /Users/peter/devel/outline/outline-client/node_modules/electron-builder-lib/src/platformPackager.ts:231:21
    at Generator.next (<anonymous>)
    at processImmediate (timers.js:632:19)
From previous event:
    at WinPackager.doPack (/Users/peter/devel/outline/outline-client/node_modules/electron-builder-lib/out/platformPackager.js:410:7)
    at /Users/peter/devel/outline/outline-client/node_modules/electron-builder-lib/src/platformPackager.ts:117:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (/Users/peter/devel/outline/outline-client/node_modules/electron-builder-lib/out/platformPackager.js:275:7)
    at /Users/peter/devel/outline/outline-client/node_modules/electron-builder-lib/src/packager.ts:373:24
    at Generator.next (<anonymous>)
    at xfs.stat (/Users/peter/devel/outline/outline-client/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /Users/peter/devel/outline/outline-client/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqCallback.oncomplete (fs.js:162:5)
From previous event:
    at Packager.doBuild (/Users/peter/devel/outline/outline-client/node_modules/electron-builder-lib/out/packager.js:615:7)
    at /Users/peter/devel/outline/outline-client/node_modules/electron-builder-lib/src/packager.ts:317:52
    at Generator.next (<anonymous>)
    at /Users/peter/devel/outline/outline-client/node_modules/graceful-fs/graceful-fs.js:99:16
    at /Users/peter/devel/outline/outline-client/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqCallback.oncomplete (fs.js:148:20)
From previous event:
    at Packager._build (/Users/peter/devel/outline/outline-client/node_modules/electron-builder-lib/out/packager.js:542:7)
    at /Users/peter/devel/outline/outline-client/node_modules/electron-builder-lib/src/packager.ts:290:23
    at Generator.next (<anonymous>)
    at processImmediate (timers.js:632:19)
From previous event:
    at Packager.build (/Users/peter/devel/outline/outline-client/node_modules/electron-builder-lib/out/packager.js:501:7)
    at /Users/peter/devel/outline/outline-client/node_modules/electron-builder-lib/src/index.ts:51:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/Users/peter/devel/outline/outline-client/node_modules/electron-builder-lib/out/index.js:220:17)
    at build (/Users/peter/devel/outline/outline-client/node_modules/electron-builder/src/builder.ts:234:10)
    at then (/Users/peter/devel/outline/outline-client/node_modules/electron-builder/src/cli/cli.ts:43:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
peter:outline-client peter$

**Comment by trevj** [comment]
@hwnahm I need more information before I can help, e.g.:
- version of Windows
- version of Node
- version of yarn
- which command you ran

**Comment by hwnahm** [comment]
version of Windows : I did it on my mac.
version of Node : v11.4.0
version of yarn : 1.12.3
which command you ran : yarn do src/electron/release

**Comment by hwnahm** [comment]
Do I need Parallels desktop?

**Comment by hwnahm** [comment]
After install Parallels Desktop and Windows 10 Home the error message is changed.
Error: Cannot find certificate Jigsaw Operations LLC, all certs: 
What I have to solve this issue? I need to buy a code signing certificate?

---------------------------------------------------------------------------------------------
 ALL DONE
+ echo '[Done src/electron/build]'
[Done src/electron/build]
  • electron-builder version=20.13.3
  • description is missed in the package.json appPackageFile=/Users/peter/devel/WTVPN/windows-v1.2.23/build/windows/package.json
  • author is missed in the package.json appPackageFile=/Users/peter/devel/WTVPN/windows-v1.2.23/build/windows/package.json
  • writing effective config file=build/windows/dist/electron-builder-effective-config.yaml
  • no native production dependencies
  • packaging       platform=win32 arch=ia32 electron=1.8.8 appOutDir=build/windows/dist/win-ia32-unpacked
Downloading tmp-7919-1-SHASUMS256.txt-1.8.8
[============================================>] 100.0% of 5.74 kB (5.74 kB/s)
Error: Cannot find certificate Jigsaw Operations LLC, all certs: 
    at /Users/peter/devel/WTVPN/windows-v1.2.23/node_modules/electron-builder-lib/src/windowsCodeSign.ts:114:12
    at Generator.next (<anonymous>)
From previous event:
    at getCertificateFromStoreInfo (/Users/peter/devel/WTVPN/windows-v1.2.23/node_modules/electron-builder-lib/src/windowsCodeSign.ts:123:2)
    at vm.value.then.vm (/Users/peter/devel/WTVPN/windows-v1.2.23/node_modules/electron-builder-lib/src/winPackager.ts:30:47)
From previous event:
    at Lazy.WinPackager.cscInfo (/Users/peter/devel/WTVPN/windows-v1.2.23/node_modules/electron-builder-lib/src/winPackager.ts:30:11)
    at Lazy.get value [as value] (/Users/peter/devel/WTVPN/windows-v1.2.23/node_modules/lazy-val/src/main.ts:18:23)
    at Lazy.<anonymous> (/Users/peter/devel/WTVPN/windows-v1.2.23/node_modules/electron-builder-lib/src/winPackager.ts:94:14)
    at Generator.next (<anonymous>)
From previous event:
    at Lazy.get value [as value] (/Users/peter/devel/WTVPN/windows-v1.2.23/node_modules/lazy-val/src/main.ts:18:23)
    at /Users/peter/devel/WTVPN/windows-v1.2.23/node_modules/electron-builder-lib/src/publish/PublishManager.ts:206:25
    at Generator.next (<anonymous>)
From previous event:
    at getAppUpdatePublishConfiguration (/Users/peter/devel/WTVPN/windows-v1.2.23/node_modules/electron-builder-lib/src/publish/PublishManager.ts:215:2)
    at /Users/peter/devel/WTVPN/windows-v1.2.23/node_modules/electron-builder-lib/src/publish/PublishManager.ts:84:9
    at Generator.next (<anonymous>)
From previous event:
    at PublishManager.packager.addAfterPackHandler (/Users/peter/devel/WTVPN/windows-v1.2.23/node_modules/electron-builder-lib/src/publish/PublishManager.ts:91:6)
    at _bluebirdLst.default.each.it (/Users/peter/devel/WTVPN/windows-v1.2.23/node_modules/electron-builder-lib/src/packager.ts:467:49)
From previous event:
    at Packager.afterPack (/Users/peter/devel/WTVPN/windows-v1.2.23/node_modules/electron-builder-lib/src/packager.ts:467:28)
    at /Users/peter/devel/WTVPN/windows-v1.2.23/node_modules/electron-builder-lib/src/platformPackager.ts:231:21
    at Generator.next (<anonymous>)
    at processImmediate (timers.js:632:19)
From previous event:
    at WinPackager.doPack (/Users/peter/devel/WTVPN/windows-v1.2.23/node_modules/electron-builder-lib/out/platformPackager.js:410:7)
    at /Users/peter/devel/WTVPN/windows-v1.2.23/node_modules/electron-builder-lib/src/platformPackager.ts:117:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (/Users/peter/devel/WTVPN/windows-v1.2.23/node_modules/electron-builder-lib/out/platformPackager.js:275:7)
    at /Users/peter/devel/WTVPN/windows-v1.2.23/node_modules/electron-builder-lib/src/packager.ts:373:24
    at Generator.next (<anonymous>)
    at xfs.stat (/Users/peter/devel/WTVPN/windows-v1.2.23/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /Users/peter/devel/WTVPN/windows-v1.2.23/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqCallback.oncomplete (fs.js:161:5)
From previous event:
    at Packager.doBuild (/Users/peter/devel/WTVPN/windows-v1.2.23/node_modules/electron-builder-lib/out/packager.js:615:7)
    at /Users/peter/devel/WTVPN/windows-v1.2.23/node_modules/electron-builder-lib/src/packager.ts:317:52
    at Generator.next (<anonymous>)
    at /Users/peter/devel/WTVPN/windows-v1.2.23/node_modules/graceful-fs/graceful-fs.js:99:16
    at /Users/peter/devel/WTVPN/windows-v1.2.23/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqCallback.args [as oncomplete] (fs.js:147:20)
From previous event:
    at Packager._build (/Users/peter/devel/WTVPN/windows-v1.2.23/node_modules/electron-builder-lib/out/packager.js:542:7)
    at /Users/peter/devel/WTVPN/windows-v1.2.23/node_modules/electron-builder-lib/src/packager.ts:290:23
    at Generator.next (<anonymous>)
    at processImmediate (timers.js:632:19)
From previous event:
    at Packager.build (/Users/peter/devel/WTVPN/windows-v1.2.23/node_modules/electron-builder-lib/out/packager.js:501:7)
    at /Users/peter/devel/WTVPN/windows-v1.2.23/node_modules/electron-builder-lib/src/index.ts:51:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/Users/peter/devel/WTVPN/windows-v1.2.23/node_modules/electron-builder-lib/out/index.js:220:17)
    at build (/Users/peter/devel/WTVPN/windows-v1.2.23/node_modules/electron-builder/src/builder.ts:234:10)
    at then (/Users/peter/devel/WTVPN/windows-v1.2.23/node_modules/electron-builder/src/cli/cli.ts:43:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by hwnahm** [comment]
Building on Windows shows ….
/tmp/yarn--1544940084518-0.6677318644823458/node: line 3: C:\nodejs\node.exe: command not found

$ yarn do src/electron/build
yarn run v1.12.3
$ bash ./scripts/do_action.sh src/electron/build
++ git rev-parse --show-toplevel
+ export ROOT_DIR=/home/peter/outline-client
+ ROOT_DIR=/home/peter/outline-client
+ export BUILD_DIR=/home/peter/outline-client/build
+ BUILD_DIR=/home/peter/outline-client/build
+ export -f do_action
+ do_action src/electron/build
+ local action=src/electron/build
+ echo '[Running src/electron/build]'
[Running src/electron/build]
+ shift
+ /home/peter/outline-client/src/electron/build_action.sh
+ /cygdrive/c/Users/peter/AppData/Roaming/npm/yarn do src/www/build
/tmp/yarn--1544940084518-0.6677318644823458/node: line 3: C:\nodejs\node.exe: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by hwnahm** [comment]
Building outline windows client on MacOS

1. Install Parallels Desktop (Evaluation Version works fine) and Windows 10
2. Create self-signed certificate
    on windows powershell : New-SelfSignedCertificate -Subject "CN=Jigsaw Operations LLC" -Type CodeSigning -CertStoreLocation Cert:\CurrentUser\My
3. yarn do src/electron/release

then ./build/windows/dist/Outline-Client.exe will be made.

**Comment by trevj** [comment]
@hwnahm `yarn do src/electron/release` builds a **signed** binary while `yarn do src/electron/package` builds an unsigned binary. Please use the latter: creating a self-signed binary in someone else's name is likely to cause you problems at some point.
