### ISSUE TITLE
cannot build on windows with latest versions of yarn

### ISSUE THREAD

**Issue by Sean-Wang** [Jigsaw-Code/outline-client#468]
C:\Users\toms\outline-client>yarn do src/electron/build
yarn run v1.12.3
$ bash ./scripts/do_action.sh src/electron/build
++ git rev-parse --show-toplevel
+ export ROOT_DIR=/mnt/c/Users/toms/outline-client
+ ROOT_DIR=/mnt/c/Users/toms/outline-client
+ export BUILD_DIR=/mnt/c/Users/toms/outline-client/build
+ BUILD_DIR=/mnt/c/Users/toms/outline-client/build
+ export -f do_action
+ do_action src/electron/build
+ local action=src/electron/build
+ echo '[Running src/electron/build]'
[Running src/electron/build]
+ shift
+ /mnt/c/Users/toms/outline-client/src/electron/build_action.sh
+ yarn do src/www/build
/mnt/c/Temp/yarn--1546159424275-0.23207095948173206/yarn: 3: /mnt/c/Temp/yarn--1546159424275-0.23207095948173206/yarn: C:\Program Files\nodejs\node.exe: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

version of Windows: Windows 10 10.0.17134.472
version of Node: v10.15.0
version of yarn: 1.12.3
which command you ran: yarn do src/electron/build

**Comment by trevj** [comment]
@Sean-Wang Sorry you've been having trouble compiling Outline. I see the same error when I install the latest versions of Yarn. As a workaround, if you install version 1.10.1 it should compile normally.

**Comment by Sean-Wang** [comment]
> @Sean-Wang Sorry you've been having trouble compiling Outline. I see the same error when I install the latest versions of Yarn. As a workaround, if you install version 1.10.1 it should compile normally:
> https://github.com/yarnpkg/yarn/releases/tag/v1.10.1

Thank you for your reply. I'll try it with yarn 1.10.1, and with more feedback.

**Comment by Sean-Wang** [comment]
Release with yarn 1.10.1, not prompted `C:\Program Files\nodejs\node.exe: not found`, but prompted:

![image](https://user-images.githubusercontent.com/1193073/50720762-072a8a00-10ee-11e9-877f-43d5410e263f.png)

which command you ran : `yarn do src/electron/release`

Use `git clone` download project.

**Comment by trevj** [comment]
@Sean-Wang Do you also have Node.js installed? For Windows, I just use an MSI from this page:
https://nodejs.org/en/download/

**Comment by trevj** [comment]
I'm going to re-open this as I would like to fix this - is an issue for newcomers to the project.

**Comment by Sean-Wang** [comment]
> @Sean-Wang Do you also have Node.js installed? For Windows, I just use an MSI from this page:
> https://nodejs.org/en/download/

I have already installed Node.js with MSI. And version of Node is `v10.15.0`.

**Comment by trevj** [comment]
@Sean-Wang Are you using Cygwin, or some other Unix-like terminal?

**Comment by Sean-Wang** [comment]
> @Sean-Wang Are you using Cygwin, or some other Unix-like terminal?

Installed Cygwin and Ubuntu in Windows 10.

**Comment by trevj** [comment]
@Sean-Wang Not sure what you mean by installing Ubuntu - all you need is Cygwin with a couple of basic tools like rsync (sorry this is not very well documented yet). Can you please paste the error message you get when you try to compile?

**Comment by Sean-Wang** [comment]
ALL DONE
+ echo '[Done src/electron/package_common]'
[Done src/electron/package_common]
  ? electron-builder version=20.34.0
  ? loaded configuration file=/mnt/e/com.goooon/outline_0111/src/electron/electron-builder.json
  ? description is missed in the package.json appPackageFile=/mnt/e/com.goooon/outline_0111/package.json
  ? author is missed in the package.json appPackageFile=/mnt/e/com.goooon/outline_0111/package.json
  ? writing effective config file=build/dist/builder-effective-config.yaml
  ? no native production dependencies
  ? packaging       platform=win32 arch=ia32 electron=2.0.16 appOutDir=build/dist/win-ia32-unpacked
Error: Exit code: ENOENT. spawn prlctl ENOENT
    at /mnt/e/com.goooon/outline_0111/node_modules/builder-util/src/util.ts:127:16
    at exithandler (child_process.js:301:5)
    at ChildProcess.errorhandler (child_process.js:313:5)
    at ChildProcess.emit (events.js:188:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:252:12)
    at onErrorNT (internal/child_process.js:421:16)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
From previous event:
    at _parseVmList (/mnt/e/com.goooon/outline_0111/node_modules/app-builder-lib/out/vm/ParallelsVm.js:88:23)
    at parseVmList (/mnt/e/com.goooon/outline_0111/node_modules/app-builder-lib/out/vm/ParallelsVm.js:52:23)
    at /mnt/e/com.goooon/outline_0111/node_modules/app-builder-lib/out/vm/vm.js:68:58
    at Generator.next (<anonymous>)
    at _getWindowsVm (/mnt/e/com.goooon/outline_0111/node_modules/app-builder-lib/out/vm/vm.js:77:24)
    at getWindowsVm (/mnt/e/com.goooon/outline_0111/node_modules/app-builder-lib/out/vm/vm.js:65:24)
    at Lazy.WinPackager.vm (/mnt/e/com.goooon/outline_0111/node_modules/app-builder-lib/src/winPackager.ts:72:109)
    at Lazy.get value [as value] (/mnt/e/com.goooon/outline_0111/node_modules/lazy-val/src/main.ts:18:23)
    at Lazy.WinPackager.cscInfo (/mnt/e/com.goooon/outline_0111/node_modules/app-builder-lib/src/winPackager.ts:33:22)
    at Lazy.get value [as value] (/mnt/e/com.goooon/outline_0111/node_modules/lazy-val/src/main.ts:18:23)
    at Lazy.<anonymous> (/mnt/e/com.goooon/outline_0111/node_modules/app-builder-lib/src/winPackager.ts:88:40)
From previous event:
    at _getWindowsVm (/mnt/e/com.goooon/outline_0111/node_modules/app-builder-lib/out/vm/vm.js:77:24)
    at getWindowsVm (/mnt/e/com.goooon/outline_0111/node_modules/app-builder-lib/out/vm/vm.js:65:24)
    at Lazy.WinPackager.vm (/mnt/e/com.goooon/outline_0111/node_modules/app-builder-lib/src/winPackager.ts:72:109)
    at Lazy.get value [as value] (/mnt/e/com.goooon/outline_0111/node_modules/lazy-val/src/main.ts:18:23)
    at Lazy.WinPackager.cscInfo (/mnt/e/com.goooon/outline_0111/node_modules/app-builder-lib/src/winPackager.ts:33:22)
    at Lazy.get value [as value] (/mnt/e/com.goooon/outline_0111/node_modules/lazy-val/src/main.ts:18:23)
    at Lazy.<anonymous> (/mnt/e/com.goooon/outline_0111/node_modules/app-builder-lib/src/winPackager.ts:88:40)
    at Generator.next (<anonymous>)
From previous event:
    at Lazy.get value [as value] (/mnt/e/com.goooon/outline_0111/node_modules/lazy-val/src/main.ts:18:23)
    at /mnt/e/com.goooon/outline_0111/node_modules/app-builder-lib/src/publish/PublishManager.ts:231:69
    at Generator.next (<anonymous>)
    at processImmediate (timers.js:632:19)
From previous event:
    at _getAppUpdatePublishConfiguration (/mnt/e/com.goooon/outline_0111/node_modules/app-builder-lib/out/publish/PublishManager.js:444:44)
    at getAppUpdatePublishConfiguration (/mnt/e/com.goooon/outline_0111/node_modules/app-builder-lib/out/publish/PublishManager.js:415:44)
    at /mnt/e/com.goooon/outline_0111/node_modules/app-builder-lib/src/publish/PublishManager.ts:100:35
    at Generator.next (<anonymous>)
From previous event:
    at /mnt/e/com.goooon/outline_0111/node_modules/app-builder-lib/src/publish/PublishManager.ts:84:5
    at _bluebirdLst.default.each.it (/mnt/e/com.goooon/outline_0111/node_modules/app-builder-lib/src/packager.ts:476:49)
From previous event:
    at Packager.afterPack (/mnt/e/com.goooon/outline_0111/node_modules/app-builder-lib/src/packager.ts:476:28)
    at /mnt/e/com.goooon/outline_0111/node_modules/app-builder-lib/src/platformPackager.ts:238:21
    at Generator.next (<anonymous>)
    at processImmediate (timers.js:632:19)
From previous event:
    at WinPackager.doPack (/mnt/e/com.goooon/outline_0111/node_modules/app-builder-lib/src/platformPackager.ts:166:165)
    at /mnt/e/com.goooon/outline_0111/node_modules/app-builder-lib/src/platformPackager.ts:112:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (/mnt/e/com.goooon/outline_0111/node_modules/app-builder-lib/src/platformPackager.ts:110:95)
    at /mnt/e/com.goooon/outline_0111/node_modules/app-builder-lib/src/packager.ts:379:24
    at Generator.next (<anonymous>)
    at xfs.stat (/mnt/e/com.goooon/outline_0111/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /mnt/e/com.goooon/outline_0111/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqCallback.oncomplete (fs.js:161:5)
From previous event:
    at Packager.doBuild (/mnt/e/com.goooon/outline_0111/node_modules/app-builder-lib/src/packager.ts:345:24)
    at /mnt/e/com.goooon/outline_0111/node_modules/app-builder-lib/src/packager.ts:315:57
    at Generator.next (<anonymous>)
    at /mnt/e/com.goooon/outline_0111/node_modules/graceful-fs/graceful-fs.js:99:16
    at /mnt/e/com.goooon/outline_0111/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqCallback.args [as oncomplete] (fs.js:147:20)
From previous event:
    at Packager._build (/mnt/e/com.goooon/outline_0111/node_modules/app-builder-lib/src/packager.ts:284:133)
    at /mnt/e/com.goooon/outline_0111/node_modules/app-builder-lib/src/packager.ts:280:23
    at Generator.next (<anonymous>)
    at processImmediate (timers.js:632:19)
From previous event:
    at Packager.build (/mnt/e/com.goooon/outline_0111/node_modules/app-builder-lib/src/packager.ts:237:14)
    at build (/mnt/e/com.goooon/outline_0111/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/mnt/e/com.goooon/outline_0111/node_modules/electron-builder/src/builder.ts:227:10)
    at then (/mnt/e/com.goooon/outline_0111/node_modules/electron-builder/src/cli/cli.ts:46:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by trevj** [comment]
@Sean-Wang `release_windows` requires our hardware signing key. Can you try `yarn do src/electron/package_windows` instead?

**Comment by Sean-Wang** [comment]
> @Sean-Wang `release_windows` requires our hardware signing key. Can you try `yarn do src/electron/package_windows` instead?

Thanks @trevj , I will try and with more feedback.
