### ISSUE TITLE
Outline Client and Ubuntu 16.04 

### ISSUE THREAD

**Issue by uhu-maotouying** [Jigsaw-Code/outline-client#552]
Opened by mistake
Please ignore

**Comment by uhu-maotouying** [comment]
Started Outline Client as sudo in Terminal
Have been asked repeatedly for my password
Have seen those Terminal messages :
uhu@uhu-E7240:~/Desktop/new outline manager$ sudo ./Outline-Client-20190914.AppImage 
[sudo] password for uhu: 
module.js:545
    throw err;
    ^

Error: Cannot find module '../dialog'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/tmp/.mount_Outlin7E3tqG/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.get [as dialog] (/tmp/.mount_Outlin7E3tqG/resources/electron.asar/browser/api/exports/electron.js:11:16)
    at process.<anonymous> (/tmp/.mount_Outlin7E3tqG/resources/electron.asar/browser/init.js:54:31)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at process._fatalException (bootstrap_node.js:383:26)
