### ISSUE TITLE
iOS build error

### ISSUE THREAD

**Issue by zeewell** [Jigsaw-Code/outline-client#608]
build failed with cmd:
```bash
yarn run clean && yarn && yarn gulp build --platform=ios
```

- yarn version v1.16.0
- nodejs version v12.3.1

the error output:
```
.......


** ARCHIVE FAILED **


The following build commands failed:
	CompileSwift normal armv7 /Users/***/Develop/opensource/outline/outline-client/platforms/ios/Outline/Plugins/cordova-plugin-outline/OutlineConnection.swift
	CompileSwift normal armv7 /Users/***/Develop/opensource/outline/outline-client/platforms/ios/Outline/Resources/vpn/OutlineConnectionStore.swift
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
	CompileSwift normal arm64 /Users/***/Develop/opensource/outline/outline-client/platforms/ios/Outline/Plugins/cordova-plugin-outline/OutlineConnection.swift
	CompileSwift normal arm64 /Users/***/Develop/opensource/outline/outline-client/platforms/ios/Outline/Resources/vpn/Subnet.swift
	CompileSwift normal arm64 /Users/***/Develop/opensource/outline/outline-client/platforms/ios/Outline/Resources/vpn/OutlineConnectionStore.swift
(6 failures)
xcodebuild: Command failed with exit code 65
[17:28:26] 'cordovaCompile' errored after 22 s
[17:28:26] Error: exited with error code: 65
    at ChildProcess.onexit (/Users/***/Develop/opensource/outline/outline-client/node_modules/end-of-stream/index.js:39:36)
    at ChildProcess.emit (events.js:200:13)
    at ChildProcess.EventEmitter.emit (domain.js:494:23)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
``` 

How to fix this?

**Comment by TedYarm** [comment]
I got the same problem with you ,could you tell me how fix it?
