### ISSUE TITLE
Fedora 30 Cannot connect to server ,disconnect almost immediately

### ISSUE THREAD

**Issue by bin-haw** [Jigsaw-Code/outline-client#638]
**Describe the bug**
Cannot connect,but the app on android is fine.
System : Fedora 30

**To Reproduce**
1. When click the bottom connect,just disconnect almost immediately

**Screenshots**

>loading web app from file:///tmp/.mount_OutlinKR11M2/resources/app.asar/www/electron_index.html
Checking for update
Error: Error: ENOENT: no such file or directory, open '/tmp/.mount_OutlinKR11M2/resources/app-update.yml'
    at /tmp/.mount_OutlinKR11M2/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:451:27
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.loadUpdateConfig (/tmp/.mount_OutlinKR11M2/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:447:33)
    at Lazy.AppUpdater.configOnDisk (/tmp/.mount_OutlinKR11M2/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:141:43)
    at Lazy.get value [as value] (/tmp/.mount_OutlinKR11M2/resources/app.asar/node_modules/lazy-val/src/main.ts:18:25)
    at /tmp/.mount_OutlinKR11M2/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:341:46
From previous event:
    at AppImageUpdater.getUpdateInfoAndProvider (/tmp/.mount_OutlinKR11M2/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:337:43)
    at /tmp/.mount_OutlinKR11M2/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:354:31
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/tmp/.mount_OutlinKR11M2/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:353:34)
    at /tmp/.mount_OutlinKR11M2/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:289:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at AppImageUpdater._checkForUpdates (/tmp/.mount_OutlinKR11M2/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:284:33)
    at AppImageUpdater.checkForUpdates (/tmp/.mount_OutlinKR11M2/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:223:35)
    at checkForUpdates (/tmp/.mount_OutlinKR11M2/resources/app.asar/build/electron/electron/index.js:366:40)
    at App.electron_1.app.on (/tmp/.mount_OutlinKR11M2/resources/app.asar/build/electron/electron/index.js:196:9)
    at emitTwo (events.js:131:20)
    at App.emit (events.js:214:7)
Outline is starting

>connecting to bxxxxxxxxx...
a helper has exited, disconnecting
all helpers have exited
disconnected from bxxxxxxxxx
connecting to bxxxxxxxxx...
a helper has exited, disconnecting
all helpers have exited
disconnected from bxxxxxxxxx
could not connect: InvalidServerCredentials (could not connect to remote test website: Socket Closed)
connecting to bxxxxxxxxx...
a helper has exited, disconnecting
all helpers have exited
disconnected from bxxxxxxxxx
could not connect: InvalidServerCredentials (could not connect to remote test website: Socket Closed)
could not connect: InvalidServerCredentials (could not connect to remote test website: Socket Closed)
Promise "DNS lookup" resolved before 10000 ms.

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version :30

**Comment by bin-haw** [comment]
emmm,I try the client on ubuntu 18.04, it connect successfully. Why I can't connect on Fedora .
The URL are the same one.

**Comment by ksalihcavusoglu** [comment]
same on windows 10
