### ISSUE TITLE
Build ios cant be finished.

### ISSUE THREAD

**Issue by TedYarm** [Jigsaw-Code/outline-client#738]
**Describe the issue**
A clear and concise description of what the issue is. If possible, paste the output from your terminal.
bogon:outline-client shield$ yarn gulp build --platform=ios
yarn run v1.16.0
$ /Users/shield/Documents/Developer/devOps/chessesVPN/outline/outline-client/node_modules/.bin/gulp build --platform=ios
[02:47:33] Using gulpfile ~/Documents/Developer/devOps/chessesVPN/outline/outline-client/gulpfile.js
[02:47:33] Starting 'build'...
[02:47:33] Starting 'buildWebApp'...
$ bash ./scripts/do_action.sh src/www/build
++ git rev-parse --show-toplevel
+ export ROOT_DIR=/Users/shield/Documents/Developer/devOps/chessesVPN/outline/outline-client
+ ROOT_DIR=/Users/shield/Documents/Developer/devOps/chessesVPN/outline/outline-client
+ export BUILD_DIR=/Users/shield/Documents/Developer/devOps/chessesVPN/outline/outline-client/build
+ BUILD_DIR=/Users/shield/Documents/Developer/devOps/chessesVPN/outline/outline-client/build
+ export -f do_action
+ do_action src/www/build
+ local action=src/www/build
+ echo '[Running src/www/build]'
+ shift
+ /Users/shield/Documents/Developer/devOps/chessesVPN/outline/outline-client/src/www/build_action.sh
[Running src/www/build]
+ tsc -p src/www
+ rsync -ac --exclude '*.ts' src/www/ www/
+ echo '[Done src/www/build]'
[Done src/www/build]
[02:47:36] Finished 'buildWebApp' after 2.96 s
[02:47:36] Starting 'copyBabelPolyfill'...
node_modules/babel-polyfill/dist/polyfill.min.js -> www/babel-polyfill.min.js
[02:47:36] Finished 'copyBabelPolyfill' after 9.75 ms
[02:47:36] Starting 'browserifyAndBabelify'...
[02:47:38] Finished 'browserifyAndBabelify' after 1.4 s
[02:47:38] Starting 'transpileBowerComponents'...
[02:47:45] Finished 'transpileBowerComponents' after 7.64 s
[02:47:45] Starting 'transpileUiComponents'...
[02:47:45] Finished 'transpileUiComponents' after 104 ms
[02:47:45] Starting 'rtlCss'...
[02:47:45] Generating RTL CSS
[02:47:45] Finished 'rtlCss' after 93 ms
[02:47:45] Starting 'writeEnvJson'...
[02:47:46] Finished 'writeEnvJson' after 332 ms
[02:47:46] Starting 'cordovaPlatformAdd'...
[02:47:46] Finished 'cordovaPlatformAdd' after 8.68 ms
[02:47:46] Starting 'cordovaPrepare'...
cordova-custom-config: Skipping auto-restore of config file backup(s)
Discovered saved plugin "cordova-plugin-clipboard". Adding it to the project

**it's just stop last line ,cant   continue with script. the ios suorce can be run, but when debug it on the iphone ,cant be start vpn server. cant saw any vpn service start.. just put right access key ,the key is running my mac ,and the other phone downloaded from app store.

**Environment**
 - OS: [IOS]
 - Yarn 1.16.0
 - Node.js v12.14.1
**Additional context**

debug on Xcode

To disable web storage backup to iCloud, set the BackupWebStorage preference to "local" in the Cordova config.xml file
2020-02-04 02:57:15.880050+0800 Outline[468:66785] [MC] Lazy loading NSBundle MobileCoreServices.framework
2020-02-04 02:57:15.881196+0800 Outline[468:66785] [MC] Loaded MobileCoreServices.framework
2020-02-04 02:57:15.884497+0800 Outline[468:66785] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2020-02-04 02:57:15.889467+0800 Outline[468:66785] Using UIWebView
2020-02-04 02:57:15.891866+0800 Outline[468:66785] [CDVTimer][console] 0.097990ms
2020-02-04 02:57:15.892024+0800 Outline[468:66785] [CDVTimer][handleopenurl] 0.091910ms
2020-02-04 02:57:15.893665+0800 Outline[468:66785] [CDVTimer][intentandnavigationfilter] 1.605988ms
2020-02-04 02:57:15.893782+0800 Outline[468:66785] [CDVTimer][gesturehandler] 0.073910ms
2020-02-04 02:57:15.893821+0800 Outline[468:66785] [CDVTimer][TotalPluginStartup] 2.115965ms
2020-02-04 02:57:15.916277+0800 Outline[468:66831] Metal API Validation Enabled
2020-02-04 02:57:15.989627+0800 Outline[468:66785] refreshPreferences: HangTracerEnabled: 0
2020-02-04 02:57:15.989700+0800 Outline[468:66785] refreshPreferences: HangTracerDuration: 500
2020-02-04 02:57:15.989730+0800 Outline[468:66785] refreshPreferences: ActivationLoggingEnabled: 0 ActivationLoggingTaskedOffByDA:0
2020-02-04 02:57:16.161641+0800 Outline[468:66785] Resetting plugins due to page load.
2020-02-04 02:57:16.193204+0800 Outline[468:66785] Failed to load webpage with error: The operation couldn’t be completed. (NSURLErrorDomain error -999.)
2020-02-04 02:57:16.193534+0800 Outline[468:66785] Resetting plugins due to page load.
2020-02-04 02:57:16.714059+0800 Outline[468:66785] Finished load of: file:///var/containers/Bundle/Application/AAAFEB02-D008-4878-B84D-79C821FEC6CF/Outline.app/www/cordova_index.html
2020-02-04 02:58:15.290917+0800 Outline[468:66785] [MC] Reading from public effective user settings.
2020-02-04 02:58:15.349237+0800 Outline[468:66785] API error: <_UIKBCompatInputView: 0x100c5f9b0; frame = (0 0; 0 0); layer = <CALayer: 0x1c0027da0>> returned 0 width, assuming UIViewNoIntrinsicMetric
2020-02-04 02:58:15.349427+0800 Outline[468:66785] API error: <_UIKBCompatInputView: 0x100c5f9b0; frame = (0 0; 0 0); layer = <CALayer: 0x1c0027da0>> returned 0 width, assuming UIViewNoIntrinsicMetric
2020-02-04 02:58:15.459861+0800 Outline[468:66785] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x1c0291f30 h=-&- v=-&- UIToolbar:0x100c4cc50.width == _UIInputViewContent:0x100c4a350.width   (active)>",
    "<NSAutoresizingMaskLayoutConstraint:0x1c0292070 h=--& v=--& _UIInputViewContent:0x100c4a350.width == 0   (active)>",
    "<NSLayoutConstraint:0x1c0284510 H:|-(8)-[_UIButtonBarStackView:0x100c4f7d0]   (active, names: '|':_UIToolbarContentView:0x100c4d090 )>",
    "<NSLayoutConstraint:0x1c02844c0 _UIButtonBarStackView:0x100c4f7d0.trailing == _UIToolbarContentView:0x100c4d090.trailing   (active)>",
    "<NSLayoutConstraint:0x1c02832f0 _UIToolbarContentView:0x100c4d090.trailing == UIToolbar:0x100c4cc50.trailing   (active)>",
    "<NSLayoutConstraint:0x1c0281680 H:|-(0)-[_UIToolbarContentView:0x100c4d090]   (active, names: '|':UIToolbar:0x100c4cc50 )>"
)

**Comment by joeysino** [comment]
Yeah installing plugins is really slow on this version of Cordova (9 is it?) and sometimes stalls.

Our solution was to copy the plugins manually, so Cordova wouldn't have to do it:

```bash
cp node_modules/cordova-plugin-* plugins/
cp node_modules/{cordova-webintent,es6-promise-plugin} plugins/
cp cordova-plugin-outline plugins/
```

Then the build completed that stage much more quickly!

**Comment by TedYarm** [comment]
> Yeah installing plugins is really slow on this version of Cordova (9 is it?) and sometimes stalls.
> 
> Our solution was to copy the plugins manually, so Cordova wouldn't have to do it:
> 
> ```shell
> cp node_modules/cordova-plugin-* plugins/
> cp node_modules/{cordova-webintent,es6-promise-plugin} plugins/
> cp cordova-plugin-outline plugins/
> ```
> 
> Then the build completed that stage much more quickly!
> 
> (For our team's convenience, we also added the entire plugins folder to git.)
> 
> Hopefully after a future Cordova upgrade, this problem will be resolved.
### ### ### ### ### ### ### 
Yeah, When I tried it ,I found the other error when I builded again. Some error show below:
If I use yarn run clean it will clean I copied  ,so I did not do yarn clean ,I copied all node_moudles to plugin , and build again ,but different error show... So could you tell what reason...?
### ### ### ### ### ### ### ### ### ### 


yarn gulp build --platform=ios
yarn run v1.16.0
The following build commands failed:
	Check dependencies
(1 failure)
xcodebuild: Command failed with exit code 65
[02:15:43] 'cordovaCompile' errored after 7.42 s
[02:15:43] Error: exited with error code: 65
    at ChildProcess.onexit (/Users/shield/outline-client/outline-client/node_modules/end-of-stream/index.js:39:36)
    at ChildProcess.emit (events.js:223:5)
    at ChildProcess.EventEmitter.emit (domain.js:498:23)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
[02:15:43] 'build' errored after 22 s
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by TedYarm** [comment]
I did that all ,but  I still got these error ....What's happen to me...

### ### ### ### ### 

=== BUILD TARGET VpnExtension OF PROJECT Outline WITH CONFIGURATION Debug ===

Check dependencies
Code Signing Error: No profiles for 'org.outline.ios.client.VpnExtension' were found:  Xcode couldn't find any iOS App Development provisioning profiles matching 'org.outline.ios.client.VpnExtension'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.
Code Signing Error: Code signing is required for product type 'App Extension' in SDK 'iOS 13.2'

** ARCHIVE FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
xcodebuild: Command failed with exit code 65
[04:19:19] 'cordovaCompile' errored after 8.89 s
[04:19:19] Error: exited with error code: 65
    at ChildProcess.onexit (/Users/shield/Documents/Developer/devOps/chessesVPN/outline/outline-client/node_modules/end-of-stream/index.js:39:36)
    at ChildProcess.emit (events.js:223:5)
    at ChildProcess.EventEmitter.emit (domain.js:498:23)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
[04:19:19] 'build' errored after 22 s
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
