### ISSUE TITLE
windows cygwin build android error.

### ISSUE THREAD

**Issue by rc452860** [Jigsaw-Code/outline-client#788]
node version:  v12.16.3
yarn version: v1.22.4

```
yarn run clean && yarn && yarn gulp build --platform=android
yarn run v1.22.4
$ rm -rf build www node_modules platforms/* plugins/*
Done in 11.77s.
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "win32" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check.
Excluding it from installation.
[3/4] Linking dependencies...
warning " > electron-promise-ipc@1.3.0" has incorrect peer dependency "electron@
^1.4.15".
warning "polymer-build > polymer-project-config@3.14.0" has incorrect peer depen
dency "polymer-analyzer@^3.0.0-pre.22".
[4/4] Building fresh packages...
$ bower install || echo no bower needed
bower cached        https://github.com/Jigsaw-Code/outline-shadowsocksconfig.git
#0.0.8
bower validate      0.0.8 against https://github.com/Jigsaw-Code/outline-shadows
ocksconfig.git#^v0.0.8
bower cached        https://github.com/PolymerElements/app-route.git#2.1.2
bower validate      2.1.2 against https://github.com/PolymerElements/app-route.g
it#^2.0.0
bower cached        https://github.com/PolymerElements/app-localize-behavior.git
#2.0.2
bower validate      2.0.2 against https://github.com/PolymerElements/app-localiz
e-behavior.git#^2.0.1
bower cached        https://github.com/PolymerElements/app-layout.git#2.1.1
bower validate      2.1.1 against https://github.com/PolymerElements/app-layout.
git#^2.0.2
bower cached        https://github.com/PolymerElements/font-roboto-local.git#1.1
.0
bower validate      1.1.0 against https://github.com/PolymerElements/font-roboto
-local.git#^1.1.0
bower cached        https://github.com/PolymerElements/iron-icons.git#2.1.1
bower validate      2.1.1 against https://github.com/PolymerElements/iron-icons.
git#^2.0.1
bower cached        https://github.com/PolymerElements/iron-iconset-svg.git#2.2.
1
bower validate      2.2.1 against https://github.com/PolymerElements/iron-iconse
t-svg.git#^2.1.0
bower cached        https://github.com/PolymerElements/paper-behaviors.git#2.1.1
bower validate      2.1.1 against https://github.com/PolymerElements/paper-behav
iors.git#^2.0.0
bower cached        https://github.com/PolymerElements/iron-pages.git#2.1.1
bower validate      2.1.1 against https://github.com/PolymerElements/iron-pages.
git#^2.0.0
bower cached        https://github.com/PolymerElements/paper-button.git#2.1.3
bower validate      2.1.3 against https://github.com/PolymerElements/paper-butto
n.git#^2.0.0
bower cached        https://github.com/PolymerElements/paper-dropdown-menu.git#2
.1.0
bower validate      2.1.0 against https://github.com/PolymerElements/paper-dropd
own-menu.git#^2.0.0
bower cached        https://github.com/PolymerElements/paper-card.git#2.1.0
bower validate      2.1.0 against https://github.com/PolymerElements/paper-card.
git#^2.0.0
bower cached        https://github.com/PolymerElements/paper-icon-button.git#2.2
.1
bower validate      2.2.1 against https://github.com/PolymerElements/paper-icon-
button.git#^2.0.1
bower cached        https://github.com/PolymerElements/paper-input.git#2.2.3
bower validate      2.2.3 against https://github.com/PolymerElements/paper-input
.git#^2.1.1
bower cached        https://github.com/PolymerElements/paper-item.git#2.1.1
bower validate      2.1.1 against https://github.com/PolymerElements/paper-item.
git#^2.0.0
bower cached        https://github.com/PolymerElements/paper-dialog.git#2.1.1
bower validate      2.1.1 against https://github.com/PolymerElements/paper-dialo
g.git#^2.0.0
bower cached        https://github.com/PolymerElements/paper-listbox.git#2.1.1
bower validate      2.1.1 against https://github.com/PolymerElements/paper-listb
ox.git#^2.0.0
bower cached        https://github.com/PolymerElements/paper-ripple.git#2.1.1
bower validate      2.1.1 against https://github.com/PolymerElements/paper-rippl
e.git#^2.0.1
bower cached        https://github.com/PolymerElements/paper-menu-button.git#2.1
.1
bower validate      2.1.1 against https://github.com/PolymerElements/paper-menu-
button.git#^2.0.0
bower cached        https://github.com/PolymerElements/paper-styles.git#2.1.0
bower validate      2.1.0 against https://github.com/PolymerElements/paper-style
s.git#^2.0.0
bower cached        https://github.com/Jigsaw-Code/outline-i18n.git#0.0.7
bower validate      0.0.7 against https://github.com/Jigsaw-Code/outline-i18n.gi
t#^0.0.7
bower cached        https://github.com/Polymer/polymer.git#2.8.0
bower validate      2.8.0 against https://github.com/Polymer/polymer.git#^2.1.0
bower cached        https://github.com/web-animations/web-animations-js.git#2.3.
2
bower validate      2.3.2 against https://github.com/web-animations/web-animatio
ns-js.git#^2.3.1
bower cached        https://github.com/PolymerElements/paper-toast.git#2.1.2
bower validate      2.1.2 against https://github.com/PolymerElements/paper-toast
.git#^2.0.0
bower cached        https://github.com/Polymer/webcomponentsjs.git#1.3.3
bower validate      1.3.3 against https://github.com/Polymer/webcomponentsjs.git
#^1.0.12
bower cached        https://github.com/yahoo/intl-messageformat.git#1.3.0
bower validate      1.3.0 against https://github.com/yahoo/intl-messageformat.gi
t#^1.0.0
bower cached        https://github.com/PolymerElements/iron-ajax.git#2.1.3
bower validate      2.1.3 against https://github.com/PolymerElements/iron-ajax.g
it#1 - 2
bower cached        https://github.com/PolymerElements/iron-location.git#2.2.2
bower validate      2.2.2 against https://github.com/PolymerElements/iron-locati
on.git#1 - 2
bower cached        https://github.com/bestiejs/punycode.js.git#1.4.1
bower validate      1.4.1 against https://github.com/bestiejs/punycode.js.git#^1
.4.1
bower cached        https://github.com/PolymerElements/iron-media-query.git#2.1.
0
bower validate      2.1.0 against https://github.com/PolymerElements/iron-media-
query.git#1 - 2
bower cached        https://github.com/PolymerElements/iron-resizable-behavior.g
it#2.1.1
bower validate      2.1.1 against https://github.com/PolymerElements/iron-resiza
ble-behavior.git#1 - 2
bower cached        https://github.com/PolymerElements/iron-flex-layout.git#2.0.
3
bower validate      2.0.3 against https://github.com/PolymerElements/iron-flex-l
ayout.git#1 - 2
bower cached        https://github.com/PolymerElements/iron-scroll-target-behavi
or.git#2.1.1
bower validate      2.1.1 against https://github.com/PolymerElements/iron-scroll
-target-behavior.git#1 - 2
bower cached        https://github.com/PolymerElements/iron-icon.git#2.1.0
bower validate      2.1.0 against https://github.com/PolymerElements/iron-icon.g
it#1 - 2
bower cached        https://github.com/PolymerElements/iron-meta.git#2.1.1
bower validate      2.1.1 against https://github.com/PolymerElements/iron-meta.g
it#1 - 2
bower cached        https://github.com/PolymerElements/iron-behaviors.git#2.1.1
bower validate      2.1.1 against https://github.com/PolymerElements/iron-behavi
ors.git#1 - 2
bower cached        https://github.com/PolymerElements/iron-checked-element-beha
vior.git#2.1.1
bower validate      2.1.1 against https://github.com/PolymerElements/iron-checke
d-element-behavior.git#1 - 2
bower cached        https://github.com/PolymerElements/iron-selector.git#2.1.0
bower validate      2.1.0 against https://github.com/PolymerElements/iron-select
or.git#1 - 2
bower cached        https://github.com/PolymerElements/iron-image.git#2.2.1
bower validate      2.2.1 against https://github.com/PolymerElements/iron-image.
git#1 - 2
bower cached        https://github.com/PolymerElements/iron-form-element-behavio
r.git#2.1.3
bower validate      2.1.3 against https://github.com/PolymerElements/iron-form-e
lement-behavior.git#1 - 2
bower cached        https://github.com/PolymerElements/iron-a11y-keys-behavior.g
it#2.1.1
bower validate      2.1.1 against https://github.com/PolymerElements/iron-a11y-k
eys-behavior.git#1 - 2
bower cached        https://github.com/PolymerElements/iron-validatable-behavior
.git#2.1.0
bower validate      2.1.0 against https://github.com/PolymerElements/iron-valida
table-behavior.git#1 - 2
bower cached        https://github.com/PolymerElements/iron-autogrow-textarea.gi
t#2.2.0
bower validate      2.2.0 against https://github.com/PolymerElements/iron-autogr
ow-textarea.git#1 - 2
bower cached        https://github.com/PolymerElements/iron-input.git#2.1.3
bower validate      2.1.3 against https://github.com/PolymerElements/iron-input.
git#1 - 2
bower cached        https://github.com/PolymerElements/neon-animation.git#2.2.1
bower validate      2.2.1 against https://github.com/PolymerElements/neon-animat
ion.git#1 - 2
bower cached        https://github.com/PolymerElements/paper-dialog-behavior.git
#2.2.2
bower validate      2.2.2 against https://github.com/PolymerElements/paper-dialo
g-behavior.git#1 - 2
bower cached        https://github.com/PolymerElements/iron-overlay-behavior.git
#2.3.4
bower validate      2.3.4 against https://github.com/PolymerElements/iron-overla
y-behavior.git#1 - 2
bower cached        https://github.com/PolymerElements/iron-menu-behavior.git#2.
1.1
bower validate      2.1.1 against https://github.com/PolymerElements/iron-menu-b
ehavior.git#1 - 2
bower cached        https://github.com/PolymerElements/iron-dropdown.git#2.2.1
bower validate      2.2.1 against https://github.com/PolymerElements/iron-dropdo
wn.git#1 - 2
bower cached        https://github.com/PolymerElements/iron-fit-behavior.git#2.2
.1
bower validate      2.2.1 against https://github.com/PolymerElements/iron-fit-be
havior.git#1 - 2
bower cached        https://github.com/webcomponents/shadycss.git#1.9.1
bower validate      1.9.1 against https://github.com/webcomponents/shadycss.git#
^v1.1.0
bower cached        https://github.com/PolymerElements/iron-a11y-announcer.git#2
.1.0
bower validate      2.1.0 against https://github.com/PolymerElements/iron-a11y-a
nnouncer.git#1 - 2
bower extra-resolution      Unnecessary resolution: polymer#^2.1.0
bower extra-resolution      Unnecessary resolution: webcomponentsjs#^1.0.12
bower install               ShadowsocksConfig#0.0.8
bower install               app-localize-behavior#2.0.2
bower install               font-roboto#1.1.0
bower install               app-route#2.1.2
bower install               app-layout#2.1.1
bower install               iron-icons#2.1.1
bower install               iron-iconset-svg#2.2.1
bower install               paper-button#2.1.3
bower install               paper-behaviors#2.1.1
bower install               iron-pages#2.1.1
bower install               paper-card#2.1.0
bower install               paper-icon-button#2.2.1
bower install               paper-dropdown-menu#2.1.0
bower install               paper-input#2.2.3
bower install               paper-item#2.1.1
bower install               paper-dialog#2.1.1
bower install               paper-listbox#2.1.1
bower install               paper-ripple#2.1.1
bower install               paper-menu-button#2.1.1
bower install               paper-styles#2.1.0
bower install               outline-i18n#0.0.7
bower install               web-animations-js#2.3.2
bower install               polymer#2.8.0
bower install               paper-toast#2.1.2
bower install               webcomponentsjs#1.3.3
bower install               intl-messageformat#1.3.0
bower install               iron-ajax#2.1.3
bower install               iron-location#2.2.2
bower install               punycode#1.4.1
bower install               iron-media-query#2.1.0
bower install               iron-flex-layout#2.0.3
bower install               iron-resizable-behavior#2.1.1
bower install               iron-scroll-target-behavior#2.1.1
bower install               iron-meta#2.1.1
bower install               iron-icon#2.1.0
bower install               iron-behaviors#2.1.1
bower install               iron-checked-element-behavior#2.1.1
bower install               iron-selector#2.1.0
bower install               iron-form-element-behavior#2.1.3
bower install               iron-image#2.2.1
bower install               iron-autogrow-textarea#2.2.0
bower install               iron-validatable-behavior#2.1.0
bower install               iron-a11y-keys-behavior#2.1.1
bower install               iron-input#2.1.3
bower install               neon-animation#2.2.1
bower install               paper-dialog-behavior#2.2.2
bower install               iron-menu-behavior#2.1.1
bower install               iron-overlay-behavior#2.3.4
bower install               iron-fit-behavior#2.2.1
bower install               iron-dropdown#2.2.1
bower install               shadycss#1.9.1
bower install               iron-a11y-announcer#2.1.0

ShadowsocksConfig#0.0.8 www\bower_components\ShadowsocksConfig
└── punycode#1.4.1

app-localize-behavior#2.0.2 www\bower_components\app-localize-behavior
├── intl-messageformat#1.3.0
├── iron-ajax#2.1.3
└── polymer#2.8.0

font-roboto#1.1.0 www\bower_components\font-roboto

app-route#2.1.2 www\bower_components\app-route
├── iron-location#2.2.2
└── polymer#2.8.0

app-layout#2.1.1 www\bower_components\app-layout
├── iron-flex-layout#2.0.3
├── iron-media-query#2.1.0
├── iron-resizable-behavior#2.1.1
├── iron-scroll-target-behavior#2.1.1
└── polymer#2.8.0

iron-icons#2.1.1 www\bower_components\iron-icons
├── iron-icon#2.1.0
├── iron-iconset-svg#2.2.1
└── polymer#2.8.0

iron-iconset-svg#2.2.1 www\bower_components\iron-iconset-svg
├── iron-meta#2.1.1
└── polymer#2.8.0

paper-button#2.1.3 www\bower_components\paper-button
├── iron-flex-layout#2.0.3
├── paper-behaviors#2.1.1
├── paper-styles#2.1.0
└── polymer#2.8.0

paper-behaviors#2.1.1 www\bower_components\paper-behaviors
├── iron-behaviors#2.1.1
├── iron-checked-element-behavior#2.1.1
├── paper-ripple#2.1.1
└── polymer#2.8.0

iron-pages#2.1.1 www\bower_components\iron-pages
├── iron-resizable-behavior#2.1.1
├── iron-selector#2.1.0
└── polymer#2.8.0

paper-card#2.1.0 www\bower_components\paper-card
├── iron-flex-layout#2.0.3
├── iron-image#2.2.1
├── paper-styles#2.1.0
└── polymer#2.8.0

paper-icon-button#2.2.1 www\bower_components\paper-icon-button
├── iron-icon#2.1.0
├── paper-behaviors#2.1.1
├── paper-styles#2.1.0
└── polymer#2.8.0

paper-dropdown-menu#2.1.0 www\bower_components\paper-dropdown-menu
├── iron-a11y-keys-behavior#2.1.1
├── iron-form-element-behavior#2.1.3
├── iron-icon#2.1.0
├── iron-iconset-svg#2.2.1
├── iron-validatable-behavior#2.1.0
├── paper-behaviors#2.1.1
├── paper-input#2.2.3
├── paper-menu-button#2.1.1
├── paper-ripple#2.1.1
├── paper-styles#2.1.0
└── polymer#2.8.0

paper-input#2.2.3 www\bower_components\paper-input
├── iron-a11y-keys-behavior#2.1.1
├── iron-autogrow-textarea#2.2.0
├── iron-behaviors#2.1.1
├── iron-form-element-behavior#2.1.3
├── iron-input#2.1.3
├── paper-styles#2.1.0
└── polymer#2.8.0

paper-item#2.1.1 www\bower_components\paper-item
├── iron-behaviors#2.1.1
├── iron-flex-layout#2.0.3
├── paper-styles#2.1.0
└── polymer#2.8.0

paper-dialog#2.1.1 www\bower_components\paper-dialog
├── iron-overlay-behavior#2.3.4
├── neon-animation#2.2.1
├── paper-dialog-behavior#2.2.2
└── polymer#2.8.0

paper-listbox#2.1.1 www\bower_components\paper-listbox
├── iron-behaviors#2.1.1
├── iron-menu-behavior#2.1.1
├── paper-styles#2.1.0
└── polymer#2.8.0

paper-ripple#2.1.1 www\bower_components\paper-ripple
├── iron-a11y-keys-behavior#2.1.1
└── polymer#2.8.0

paper-menu-button#2.1.1 www\bower_components\paper-menu-button
├── iron-a11y-keys-behavior#2.1.1
├── iron-behaviors#2.1.1
├── iron-dropdown#2.2.1
├── iron-fit-behavior#2.2.1
├── neon-animation#2.2.1
├── paper-styles#2.1.0
└── polymer#2.8.0

paper-styles#2.1.0 www\bower_components\paper-styles
├── font-roboto#1.1.0
├── iron-flex-layout#2.0.3
└── polymer#2.8.0

outline-i18n#0.0.7 www\bower_components\outline-i18n

web-animations-js#2.3.2 www\bower_components\web-animations-js

polymer#2.8.0 www\bower_components\polymer
├── shadycss#1.9.1
└── webcomponentsjs#1.3.3

paper-toast#2.1.2 www\bower_components\paper-toast
├── iron-a11y-announcer#2.1.0
├── iron-fit-behavior#2.2.1
├── iron-overlay-behavior#2.3.4
└── polymer#2.8.0

webcomponentsjs#1.3.3 www\bower_components\webcomponentsjs

intl-messageformat#1.3.0 www\bower_components\intl-messageformat

iron-ajax#2.1.3 www\bower_components\iron-ajax
└── polymer#2.8.0

iron-location#2.2.2 www\bower_components\iron-location
└── polymer#2.8.0

punycode#1.4.1 www\bower_components\punycode

iron-media-query#2.1.0 www\bower_components\iron-media-query
└── polymer#2.8.0

iron-flex-layout#2.0.3 www\bower_components\iron-flex-layout
└── polymer#2.8.0

iron-resizable-behavior#2.1.1 www\bower_components\iron-resizable-behavior
└── polymer#2.8.0

iron-scroll-target-behavior#2.1.1 www\bower_components\iron-scroll-target-behavi
or
└── polymer#2.8.0

iron-meta#2.1.1 www\bower_components\iron-meta
└── polymer#2.8.0

iron-icon#2.1.0 www\bower_components\iron-icon
├── iron-flex-layout#2.0.3
├── iron-meta#2.1.1
└── polymer#2.8.0

iron-behaviors#2.1.1 www\bower_components\iron-behaviors
├── iron-a11y-keys-behavior#2.1.1
└── polymer#2.8.0

iron-checked-element-behavior#2.1.1 www\bower_components\iron-checked-element-be
havior
├── iron-form-element-behavior#2.1.3
├── iron-validatable-behavior#2.1.0
└── polymer#2.8.0

iron-selector#2.1.0 www\bower_components\iron-selector
└── polymer#2.8.0

iron-form-element-behavior#2.1.3 www\bower_components\iron-form-element-behavior
└── polymer#2.8.0

iron-image#2.2.1 www\bower_components\iron-image
└── polymer#2.8.0

iron-autogrow-textarea#2.2.0 www\bower_components\iron-autogrow-textarea
├── iron-behaviors#2.1.1
├── iron-flex-layout#2.0.3
├── iron-validatable-behavior#2.1.0
└── polymer#2.8.0

iron-validatable-behavior#2.1.0 www\bower_components\iron-validatable-behavior
├── iron-meta#2.1.1
└── polymer#2.8.0

iron-a11y-keys-behavior#2.1.1 www\bower_components\iron-a11y-keys-behavior
└── polymer#2.8.0

iron-input#2.1.3 www\bower_components\iron-input
├── iron-a11y-announcer#2.1.0
├── iron-validatable-behavior#2.1.0
└── polymer#2.8.0

neon-animation#2.2.1 www\bower_components\neon-animation
├── iron-resizable-behavior#2.1.1
├── iron-selector#2.1.0
└── polymer#2.8.0

paper-dialog-behavior#2.2.2 www\bower_components\paper-dialog-behavior
├── iron-overlay-behavior#2.3.4
├── paper-styles#2.1.0
└── polymer#2.8.0

iron-menu-behavior#2.1.1 www\bower_components\iron-menu-behavior
├── iron-a11y-keys-behavior#2.1.1
├── iron-flex-layout#2.0.3
├── iron-selector#2.1.0
└── polymer#2.8.0

iron-overlay-behavior#2.3.4 www\bower_components\iron-overlay-behavior
├── iron-a11y-keys-behavior#2.1.1
├── iron-fit-behavior#2.2.1
├── iron-resizable-behavior#2.1.1
└── polymer#2.8.0

iron-fit-behavior#2.2.1 www\bower_components\iron-fit-behavior
└── polymer#2.8.0

iron-dropdown#2.2.1 www\bower_components\iron-dropdown
├── iron-behaviors#2.1.1
├── iron-overlay-behavior#2.3.4
├── neon-animation#2.2.1
└── polymer#2.8.0

shadycss#1.9.1 www\bower_components\shadycss

iron-a11y-announcer#2.1.0 www\bower_components\iron-a11y-announcer
└── polymer#2.8.0
Done in 45.84s.
yarn run v1.22.4
$ C:\Users\rc452\Documents\workspace\outline-client\node_modules\.bin\gulp build
 --platform=android
[00:09:28] Using gulpfile ~\Documents\workspace\outline-client\gulpfile.js
[00:09:28] Starting 'build'...
[00:09:28] Starting 'buildWebApp'...
$ bash ./scripts/do_action.sh src/www/build
++ git rev-parse --show-toplevel
+ export ROOT_DIR=C:/Users/rc452/Documents/workspace/outline-client
+ ROOT_DIR=C:/Users/rc452/Documents/workspace/outline-client
[Running src/www/build]
+ export BUILD_DIR=C:/Users/rc452/Documents/workspace/outline-client/build
+ BUILD_DIR=C:/Users/rc452/Documents/workspace/outline-client/build
+ export -f do_action
+ do_action src/www/build
+ local action=src/www/build
+ echo '[Running src/www/build]'
+ shift
+ C:/Users/rc452/Documents/workspace/outline-client/src/www/build_action.sh
+ tsc -p src/www
+ rsync -ac --exclude '*.ts' src/www/ www/
+ echo '[Done src/www/build]'
[Done src/www/build]
[00:09:33] Finished 'buildWebApp' after 5.33 s
[00:09:33] Starting 'copyBabelPolyfill'...
'node_modules/babel-polyfill/dist/polyfill.min.js' -> 'www/babel-polyfill.min.js
'
[00:09:33] Finished 'copyBabelPolyfill' after 151 ms
[00:09:33] Starting 'browserifyAndBabelify'...
[00:09:36] Finished 'browserifyAndBabelify' after 2.8 s
[00:09:36] Starting 'transpileBowerComponents'...
[00:09:46] Finished 'transpileBowerComponents' after 10 s
[00:09:46] Starting 'transpileUiComponents'...
[00:09:46] Finished 'transpileUiComponents' after 116 ms
[00:09:46] Starting 'rtlCss'...
[00:09:46] Generating RTL CSS
[00:09:46] Finished 'rtlCss' after 109 ms
[00:09:46] Starting 'writeEnvJson'...
[00:09:47] Finished 'writeEnvJson' after 372 ms
[00:09:47] Starting 'cordovaPlatformAdd'...

You have been opted out of telemetry. To change this, run: cordova telemetry on.
Using cordova-fetch for cordova-android@^8.0.0
Adding android project...
Creating Cordova project for the Android platform:
        Path: platforms\android
        Package: org.outline.android.client
        Name: Outline
        Activity: MainActivity
        Android target: android-28
Subproject Path: CordovaLib
Subproject Path: app
Android project created with cordova-android@8.0.0
Discovered saved plugin "cordova-custom-config". Adding it to the project
Installing "cordova-custom-config" for android
Adding cordova-custom-config to package.json
Discovered saved plugin "cordova-plugin-device". Adding it to the project
Installing "cordova-plugin-device" for android
Adding cordova-plugin-device to package.json
Discovered saved plugin "cordova-plugin-outline". Adding it to the project
Installing "cordova-plugin-outline" for android
Copying Android third party libraries...
�����﷨����ȷ��
Failed to install 'cordova-plugin-outline': Error: Command failed: mkdir -p plug
ins/cordova-plugin-outline/android/libs/arm64-v8a/
�����﷨����ȷ��

    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at C:\Users\rc452\Documents\workspace\outline-client\plugins\cordova-plugin-
outline\android\scripts\copy_third_party.js:23:19
    at Array.forEach (<anonymous>)
    at module.exports (C:\Users\rc452\Documents\workspace\outline-client\plugins
\cordova-plugin-outline\android\scripts\copy_third_party.js:21:49)
    at runScriptViaModuleLoader (C:\Users\rc452\Documents\workspace\outline-clie
nt\node_modules\cordova-lib\src\hooks\HooksRunner.js:181:32)
    at runScript (C:\Users\rc452\Documents\workspace\outline-client\node_modules
\cordova-lib\src\hooks\HooksRunner.js:157:16)
    at C:\Users\rc452\Documents\workspace\outline-client\node_modules\cordova-li
b\src\hooks\HooksRunner.js:125:20
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Failed to restore plugin "cordova-plugin-outline" from config.xml. You might nee
d to try adding it again. Error: Error: Command failed: mkdir -p plugins/cordova
-plugin-outline/android/libs/arm64-v8a/
�����﷨����ȷ��

Discovered saved plugin "cordova-plugin-splashscreen". Adding it to the project
Installing "cordova-plugin-splashscreen" for android
Adding cordova-plugin-splashscreen to package.json
Discovered saved plugin "cordova-plugin-statusbar". Adding it to the project
Installing "cordova-plugin-statusbar" for android
Adding cordova-plugin-statusbar to package.json
Discovered saved plugin "cordova-plugin-whitelist". Adding it to the project
Installing "cordova-plugin-whitelist" for android
Adding cordova-plugin-whitelist to package.json
Discovered saved plugin "cordova-plugin-clipboard". Adding it to the project
Installing "cordova-plugin-clipboard" for android
Adding cordova-plugin-clipboard to package.json
Discovered saved plugin "cordova-webintent". Adding it to the project
Installing "cordova-webintent" for android
Adding cordova-webintent to package.json
cordova-custom-config: Applied custom config from config.xml to C:\Users\rc452\D
ocuments\workspace\outline-client\platforms\android\app\src\main\AndroidManifest
.xml
[00:14:06] 'cordovaPlatformAdd' errored after 4.32 min
[00:14:06] Error: exited with error code: 1
    at ChildProcess.onexit (C:\Users\rc452\Documents\workspace\outline-client\no
de_modules\end-of-stream\index.js:39:36)
    at ChildProcess.emit (events.js:310:20)
    at ChildProcess.EventEmitter.emit (domain.js:505:15)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
[00:14:06] 'build' errored after 4.63 min
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.
```

**Comment by rc452860** [comment]
There is no such problem on Mac.

**Comment by alalamav** [comment]
Hi @rc452860, I see that `mkdir -p plug
ins/cordova-plugin-outline/android/libs/arm64-v8a/` fails. We often run into issues in cygwin with absolute paths. In this case I'm not sure why the failure happens.

Are you able to run this command by itself in cygwin?

**Comment by rc452860** [comment]
> Hi @rc452860, I see that `mkdir -p plugins/cordova-plugin-outline/android/libs/arm64-v8a/` fails. We often run into issues in cygwin with absolute paths. In this case I'm not sure why the failure happens.
> 
> Are you able to run this command by itself in cygwin?

yes i can run `mkdir -p plugins/cordova-plugin-outline/android/libs/arm64-v8a/` in cygwin, I tried it without error. An error will be reported only when the `yarn gulp build --platform=android`

**Comment by freekingg** [comment]
I had the same problem

Failed to install 'cordova-plugin-outline': Error: Command failed: mkdir -p plugins/cordova-plugin-outline/android/libs/arm64-v8a/
�����﷨����ȷ��

**Comment by freekingg** [comment]
我用 gitbash成功了

**Comment by cjhenck** [comment]
May I ask what your goal is with using cygwin vs. Windows Subsystem for Linux or the native build?

**Comment by iMrDJAi** [comment]
Same issue people :/
```shell
$ cordova plugin add file:dependencies/cordova-plugin-outline
Installing "cordova-plugin-outline" for android
Copying Android third party libraries...
The syntax of the command is incorrect.
Failed to install 'cordova-plugin-outline': Error: Command failed: mkdir -p plugins/cordova-plugin-outline/android/libs/arm64-v8a/
The syntax of the command is incorrect.

    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at E:\Projects\Electron.js_Mobile\dz.imrdjai.electronjsmobile\plugins\cordova-plugin-outline\android\scripts\copy_third_party.js:23:19
    at Array.forEach (<anonymous>)
    at module.exports (E:\Projects\Electron.js_Mobile\dz.imrdjai.electronjsmobile\plugins\cordova-plugin-outline\android\scripts\copy_third_party.js:21:49)
    at runScriptViaModuleLoader (C:\Users\DjGam\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:157:32)
    at runScript (C:\Users\DjGam\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:136:12)
    at C:\Users\DjGam\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:108:40
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Command failed: mkdir -p plugins/cordova-plugin-outline/android/libs/arm64-v8a/
The syntax of the command is incorrect.
```
Any solutions?
