### ISSUE TITLE
Frequent disconnects due to subprocess errors

### ISSUE THREAD

**Issue by hilt86** [Jigsaw-Code/outline-client#834]
**Describe the bug**
When connected to an Outline server I lose Internet connectivity multiple times a day. Re-connecting fixes the issue for a while. See below for errors from the OutlineService

**To Reproduce**
1. Connect to an outline server
2. Wait for Internet connectivity to be interrupted...

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Browser:  Chrome
 - Version: Windows 10 18363 (1909)

**Event logs**

'''
First, from source OutlineService "failed to unblock IPv6: command exited with 1 (stdout: Element not found., stderr: )"
Then "failed to delete LAN bypass routes: command exited with 0 (stdout: , stderr: The route deletion failed: Element not found.)"
Then a warning "failed to stop smartdnsblock: could not kill smartdnsblock: command exited with 1 (stdout: , stderr: stop-process : Cannot find a process with the name "smartdnsblock". Verify the process name and call the cmdlet again.At line:1 char:1+ stop-process -name smartdnsblock+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : ObjectNotFound: (smartdnsblock:String) [Stop-Process], ProcessCommandException + FullyQualifiedErrorId : NoProcessFoundForGivenName,Microsoft.PowerShell.Commands.StopProcessCommand)"
Then information : "outgoing message: {"action":"resetRouting","statusCode":0,"errorMessage":null,"connectionStatus":0}"
Finally another error "Failed to handle connection: System.IO.IOException: Pipe is broken.

at System.IO.Pipes.PipeStream.WinIOError(Int32 errorCode)

at System.IO.Pipes.PipeStream.BeginWriteCore(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state)

at System.IO.Pipes.PipeStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)

at System.IO.Pipes.PipeStream.Write(Byte[] buffer, Int32 offset, Int32 count)

at OutlineService.OutlineService.WriteResponse(ServiceResponse response)

at OutlineService.OutlineService.HandleConnection(IAsyncResult result)
'''

**Submit Feedback**
Please submit feedback through the app and label it with this issue number.

**Comment by slaphead** [comment]
I am experiencing the same issues on MacOS Catalina 10.15.6. I am struggling to find where the logs are however, all I can report for now is the connection is unstable to the server. It drops a few times a day and reconnects and this is of course very irritating.

If you could let me know where to get some logs I will go through them and paste here.

**Comment by fortuna** [comment]
@hilt86 is this still an issue? What's the version of the client you are using?

**Comment by hilt86** [comment]
@fortuna I will see if I can produce this error again. I'm on v1.4
