### ISSUE TITLE
“RemoteServiceException: Bad notification for startForeground” on Android 10

### ISSUE THREAD

**Issue by GrantASL19** [Jigsaw-Code/outline-client#951]
**Describe the bug**
We’re seeing the following error reported from devices running Android 10:

```
android.app.RemoteServiceException: Bad notification for startForeground
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2137)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loop(Looper.java:237)
    at android.app.ActivityThread.main(ActivityThread.java:7948)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
```

A Samsung Galaxy Note 9 user running Android 10 reported:

> sometimes causes Samsung one UI home to crash rapidly (until you force stop beepass and start it again)

We haven‘t definitively connected this report to the error — it’s just my best guess. Also note that while this user is reporting a Samsung UI crash, we’re seeing this same issue reported from non-Samsung devices.

This is happening in [our BeePass fork](https://github.com/ASL-19/beepassvpn-client), which is based on da578698f6cd41fcfe1ced2ead075bb53bb3243b with some UI, branding, and naming modifications. Because we haven’t modified the Java code at all I’m fairly confident this isn’t a result of our changes.

**To Reproduce**
We don‘t yet have a reliable reproduction, but this appears to be similar to #280 and #287.

**Expected behavior**
The app should behave as expected on Android 10.

**Screenshots**
(N/A)

**Client System (please complete the following information):**
 - Outline Client Version: `daily-2020-12-17`
 - Your Operating System: Android 10

**Submit Feedback**
(N/A)

**Additional context**
Please let us know if you need more information and/or a reliable reproduction.

Thanks!

**Comment by alalamav** [comment]
Hi @GrantASL19, thank you for filing this issue. I have been tracking it as well, but have not been able to reproduce it or find much information about it online. I believe it's not restricted to Android 10, but I suspect it happens with custom Android distributions (i.e. Samsung).

We have unreleased changes to run the VPN service in a separate process. I'm hoping that may help. It would be very useful if you figure out a reliable reproduction so we can understand it and fix it.

**Comment by GrantASL19** [comment]
Thanks @alalamav! I’ve asked our Outreach team for any similar feedback — will report back if we get anything.

I want to try to reproduce but we don’t currently have any physical device with custom Android distributions. If we can’t figure it out we may get one for internal testing.
